defmodule Mutare.Ignore do
  @moduledoc """
  Suppresses selected mutants with a source comment. Ignored mutants remain in the report but are excluded from the mutation score. Their generated code is omitted from the metamutant, reducing compiler input and preventing their replacements from poisoning the build. They retain their IDs, reasons, and positions within `:max_mutants`.

  A trailing directive applies to its own line. A standalone directive applies to the next line of code, reading through any comment lines in between — so it works at either end of an explanatory comment block:

      expression() # mutare:ignore
      # mutare:ignore
      expression()
      # mutare:ignore[integer] checked by the boundary test;
      # any non-empty replacement is behaviorally equivalent
      expression()

  A blank line ends the comment block: the directive then targets the blank line and suppresses nothing (warned — see below).

  A plain `# mutare:ignore` covers exactly **one** line of code (see "Scoped directives" below for regions and whole files). For a multi-line expression, place it directly above the line that carries the mutated code — above the `|>` step containing it, not the pipe's first line:

      digested_files
      # mutare:ignore[atom] delivery order is discarded
      |> Task.async_stream(&write/1, ordered: false)
      |> Stream.run()

  A directive misplaced onto an earlier line of the same expression suppresses nothing; the resulting warning points at the line that has the matching mutants.

  A directive may include a family filter, a reason, or both:

      # mutare:ignore                              suppress every mutant on the line
      # mutare:ignore equivalent under int math    suppress all; record the reason
      # mutare:ignore[arithmetic]                  suppress only arithmetic mutants
      # mutare:ignore[arithmetic, relational]      suppress two families
      # mutare:ignore[relational:>]                suppress only the `i > j` swap
      # mutare:ignore[integer] off-by-one is fine  a filter and a reason together

  Filter entries are mutator family names from `Mutare.Mutators.families/0` or a custom mutator's `c:Mutare.Mutator.name/0`. Without a filter, the directive suppresses every mutant on the line.

  ## Scoped directives: regions and whole files

  Annotating a large low-value span line by line — a literal lookup table, a generated module — doesn't scale, so two scoped verbs suppress in bulk. Both take the same optional `[...]` filter and reason as `# mutare:ignore`:

      # mutare:ignore-start spot-checked; exhaustively covered by the round-trip test
      def encode(?A), do: ?B
      def encode(?B), do: ?C
      def encode(?C), do: ?D
      # mutare:ignore-end

  An `# mutare:ignore-start` opens a region and the next `# mutare:ignore-end` closes it; every mutant on the delimiter comments' lines and between them is suppressed (the span is **inclusive** of both delimiter lines, so a trailing `-start` or `-end` on a code line covers that line's mutants too). Text after `# mutare:ignore-end` is plain prose — the filter and reason belong on the `-start`.

  `# mutare:ignore-file`, anywhere in a file (conventionally at the top), suppresses every matching mutant in that file:

      # mutare:ignore-file generated by `mix gen.unicode_tables` — do not hand-edit

  A broken region pairing is a hard `Mutare.Ignore.SpecError`, not a warning: an `-end` with no open `-start`, a second `-start` inside an open region (regions don't nest), or a `-start` never closed each abort the run — the mistake is provable, and both lenient readings fail the wrong way (silently suppressing to end-of-file, or silently suppressing nothing).

  When several directives match one mutant, the most specific filter wins (`[family:label]` over `[family]` over unfiltered); on a tie, the narrowest scope (line over region over file), so the recorded reason is the most locally-written one. Scoped directives are held to the same ineffectiveness bar as line directives: an `-file` or region that suppresses nothing is warned (and aborts under `--strict-ignores`).

  Use `family:label` to select one variant from a family. For example, `[relational:<=]` suppresses the `<=` replacement but not the other relational replacements. Labels are declared by each family and matched case-insensitively. If a mutant has several labels, any matching label suppresses it. Run `mix mutare --list-mutators` for the complete built-in list.

  Text after the keyword or filter is stored as the ignore reason and shown in the report.

  ## A recognizable equivalent mutant: the re-stated delegate guard

  A pattern worth knowing when triaging `guard_drop`/`pattern_guard` survivors in wrapper-heavy code — a thin wrapper that re-states the guard of the function it delegates to:

      def sign(data, salt) when is_binary(salt),
        do: Plug.Crypto.sign(data, salt)   # Plug.Crypto.sign/2 has the identical guard

  Dropping the wrapper's guard is provably unobservable: a bad input still raises the same `FunctionClauseError`, one stack frame deeper, inside the delegate. Verify against the delegate's source (the guards must really be equivalent), then ignore with a reason naming it:

      # mutare:ignore[guard_drop] Plug.Crypto.sign/2 re-checks is_binary(salt)
      def sign(data, salt) when is_binary(salt), do: Plug.Crypto.sign(data, salt)

  This shape recurs constantly in real codebases (any module wrapping a well-guarded library); recognizing it saves convincing yourself a survivor is "just uncovered" when it is actually unreachable.

  ## When a directive errors or does nothing

  An unknown label for a built-in family, including a disabled one, or an active custom family is an error. Unknown families, bare-family typos, empty filters, and malformed filters match nothing. Any directive that suppresses no mutant produces a warning; `--strict-ignores` turns that warning into a non-zero exit.

  The `mutare:` comment namespace is reserved. A comment that starts with `# mutare:` but does not spell a recognized directive — a typo (`# mutare:ingore`), a stray space after the colon (`# mutare: ignore`), or a directive from a future Mutare version — is never silently inert: it produces the same scan-time warning, and `--strict-ignores` the same non-zero exit.

  Only source comments are parsed. Text such as `"# mutare:ignore"` inside a string has no effect.
  """

  alias Mutare.Ignore.Directive
  alias Mutare.Ignore.Directives
  alias Mutare.Ignore.SpecError
  alias Mutare.Mutator

  # A comment whose content is a directive: `#`, optional whitespace, then one of the
  # `mutare:ignore` verbs — bare, or scoped with a `-file`/`-start`/`-end` suffix (the `scope`
  # capture) — at the end of the verb token. Anchored at the comment's start, so the directive
  # must be the comment's purpose — not text buried in prose. The `rest` capture is everything
  # after the verb (the filter and/or reason). The boundary is `(?![\w-])`, not `\b`: a hyphen
  # extends the *verb* (`mutare:ignore-lines` is an unknown verb, warned via
  # `unknown_directives/1`), never starts a reason — a plain `\b` would silently read it as
  # ignore-everything with reason `-lines`. The same lookahead sits after the suffix
  # alternation, so `ignore-startx` backtracks out of the group, fails the bare boundary on its
  # `-`, and lands in the unknown-verb warning too.
  @directive ~r/\A#\s*mutare:ignore(?:-(?<scope>file|start|end))?(?![\w-])(?<rest>.*)/s

  # Any comment that *claims* the reserved namespace: `#`, optional whitespace, then
  # `mutare:`, with the same comment-start anchoring as `@directive`. A superset of
  # `@directive` — a match no directive regex recognizes is an unknown-verb comment
  # (see `unknown_directives/1`). Prose that merely mentions `mutare:` mid-comment
  # does not match.
  @namespace ~r/\A#\s*mutare:/

  # The namespace head, echoed back in the unknown-verb warning: `mutare:` plus the
  # (possibly space-detached) verb token after it, exactly as the user spaced it.
  @head ~r/mutare:\s*(?<verb>[\w-]*)/

  # Every verb the namespace recognizes today. A future directive must be added here
  # (with its own parser) for its comments to stop being warned as unknown.
  @known_verbs ~w(ignore ignore-file ignore-start ignore-end)

  # Inside `rest`, a leading `[...]` filter group and the trailing reason. The
  # filter body is everything up to the first `]`; the reason is whatever
  # follows. Only tried when `rest` starts with `[`.
  @filter ~r/\A\[(?<families>[^\]]*)\](?<reason>.*)/s

  @doc false
  # The suppression directives in `source` — the line-scoped `# mutare:ignore`s grouped by
  # suppressed line, plus the scoped `# mutare:ignore-file`s and paired
  # `# mutare:ignore-start`/`-end` regions — as one `Mutare.Ignore.Directives` container.
  @spec directives(String.t()) :: Directives.t()
  def directives(source) when is_binary(source) do
    source
    |> Sourceror.parse_string!()
    |> directives_from_ast()
  end

  @doc false
  # Like `directives/1`, but for an AST `Sourceror` already parsed. This is the **one** walk the
  # directive machinery makes over a file: `Mutare.Transform` runs it on the AST it parsed for
  # the transform, and the container it returns carries everything the scan's diagnostics later
  # read — the directives, the unknown-verb comments (`unknown`), and the expression end lines
  # the misplacement hint is bounded by (`end_lines`) — so `Mutare.Schema` never re-parses a
  # source to diagnose it.
  #
  # Region pairing never raises here: a pairing mistake is recorded under the container's
  # `scope_errors` (in document order) for `validate_scopes!/2` to turn into a hard error once a
  # file name is in hand, so the read-only diagnostics walks can parse any source.
  @spec directives_from_ast(Macro.t()) :: Directives.t()
  def directives_from_ast(ast) do
    all = comments(ast)

    # The lines occupied by *standalone* comments (`previous_eol_count > 0` ⇒ nothing else on the
    # line): the contiguous block a standalone directive reads through to find its code line. A
    # trailing comment's line carries code, so it must NOT be read through — hence standalone only.
    comment_lines =
      all
      |> Enum.filter(&(&1.previous_eol_count > 0))
      |> MapSet.new(& &1.line)

    {scoped_tokens, line_tokens} =
      all
      # Each directive comment is matched against `@directive` exactly once, here: the token
      # carries the verb's scope and the text after the verb, and every consumer below reads
      # the token rather than re-matching.
      |> Enum.flat_map(fn comment ->
        case parse_directive(comment) do
          nil -> []
          {scope, rest} -> [{comment, scope, rest}]
        end
      end)
      # Put the directives in document (source) order, then stamp each with that order as its
      # `source_order`. `comments/1` accumulates in `prewalk` *visit* order — not document order —
      # so sort by the comment's own physical line (stable, so the rare two comments sharing a line
      # keep their gathered order). The stamped index is what `directive_for/4` ranks ties on, so
      # the sort and the index that depends on it live together here, not three frames apart.
      # Reordering only matters when two directives land on the *same* suppressed line but come
      # from two *different* AST nodes (the only observable effect is on the tie-break's
      # `source_order`, compared only within one line's group) — a layout normal source can't
      # produce (a line's own directives all land as leading/trailing comments of the one node on
      # it, already document-ordered). Region pairing is also order-sensitive, and reads the same
      # sorted stream.
      # mutare:ignore[call_removal] equivalent for realistic source, per above
      |> Enum.sort_by(fn {comment, _scope, _rest} -> comment.line end)
      |> Enum.with_index()
      # One document-order index domain across *all* directive comments (scoped ones included, and
      # the `-end` delimiters, which produce no directive) — gaps are fine, comparability is what
      # the tie-break needs.
      |> Enum.split_with(fn {{_comment, scope, _rest}, _order} -> scope != :line end)

    {scoped, scope_errors} = pair_scoped(scoped_tokens)

    by_line =
      line_tokens
      |> Enum.map(fn {{comment, :line, rest}, order} ->
        to_directive(comment, rest, order, comment_lines)
      end)
      |> Enum.group_by(& &1.line)

    %Directives{
      by_line: by_line,
      scoped: scoped,
      scope_errors: scope_errors,
      unknown: unknown_verbs(all),
      end_lines: expression_end_lines(ast, Map.keys(by_line))
    }
  end

  # Read a comment as a directive: `{scope, rest}` — the verb's scope (`:line` for the bare
  # `ignore`, else `:file`/`:start`/`:end`) and everything after the verb (the filter and/or
  # reason) — or `nil` for any other comment.
  defp parse_directive(%{text: text}) do
    case Regex.named_captures(@directive, text) do
      %{"scope" => "", "rest" => rest} -> {:line, rest}
      %{"scope" => scope, "rest" => rest} -> {String.to_existing_atom(scope), rest}
      nil -> nil
    end
  end

  # Pair the scoped directive comments (in document order) into `:file` directives and
  # `{:region, first, last}` directives. Regions pair a `-start` with the next `-end`, spanning
  # both delimiter comments' lines inclusive; the filter and reason are the `-start`'s (text after
  # an `-end` is prose, never parsed). Mistakes accumulate as errors rather than raising:
  #
  #   * an `-end` with no open `-start` → `{:unmatched_end, line}`;
  #   * a `-start` inside an open region → `{:nested_region, line, open_line}` (regions don't
  #     nest; the open region stays open, so its eventual `-end` still closes it);
  #   * a `-start` still open at end of file → `{:unterminated_region, line}`.
  defp pair_scoped(tokens) do
    {directives, open, errors} =
      Enum.reduce(tokens, {[], nil, []}, fn {{comment, scope, rest}, order},
                                            {directives, open, errors} ->
        case {scope, open} do
          {:file, _open} ->
            {[scoped_directive(comment, rest, order, :file) | directives], open, errors}

          {:start, nil} ->
            {directives, {comment, rest, order}, errors}

          {:start, {open_comment, _rest, _order}} ->
            {directives, open, [{:nested_region, comment.line, open_comment.line} | errors]}

          {:end, {start_comment, start_rest, order}} ->
            region = {:region, start_comment.line, comment.line}

            {[scoped_directive(start_comment, start_rest, order, region) | directives], nil,
             errors}

          {:end, nil} ->
            {directives, nil, [{:unmatched_end, comment.line} | errors]}
        end
      end)

    errors =
      case open do
        nil -> errors
        {comment, _rest, _order} -> [{:unterminated_region, comment.line} | errors]
      end

    {Enum.reverse(directives), Enum.reverse(errors)}
  end

  # A `:file` or region directive from its (start) comment's `rest`: the filter/reason grammar
  # after the verb is exactly the line directive's; `line` is the comment's own line (a region's
  # `first`), so line-keyed sorts stay total across scopes.
  defp scoped_directive(%{line: line}, rest, source_order, scope) do
    {mutators, reason} = parse_rest(rest)

    %Directive{
      scope: scope,
      line: line,
      comment_line: line,
      mutators: mutators,
      reason: reason,
      source_order: source_order
    }
  end

  @doc false
  # Raise a `Mutare.Ignore.SpecError` for the first (document-order) region-pairing mistake in
  # `directives` — an `# mutare:ignore-end` with no open `-start`, a nested `-start`, or a
  # `-start` never closed. Pairing mistakes are hard errors, not soft `ineffective` warnings: the
  # mistake is provable from the delimiters alone, and the lenient readings both fail the wrong
  # way (suppressing to end-of-file over-suppresses; suppressing nothing silently runs mutants
  # the user asked to skip). `file` locates the error. Returns `:ok` when the scopes are sound.
  @spec validate_scopes!(Directives.t(), String.t()) :: :ok
  def validate_scopes!(%Directives{scope_errors: []}, _file), do: :ok

  def validate_scopes!(%Directives{scope_errors: [error | _rest]}, file) do
    {reason, line, message} = scope_error_message(error, file)
    raise SpecError, reason: reason, file: file, line: line, message: message
  end

  defp scope_error_message({:unmatched_end, line}, file) do
    {:unmatched_end, line,
     "#{file}:#{line}: # mutare:ignore-end without a preceding # mutare:ignore-start"}
  end

  defp scope_error_message({:nested_region, line, open_line}, file) do
    {:nested_region, line,
     "#{file}:#{line}: # mutare:ignore-start inside the region opened at line #{open_line} — " <>
       "regions don't nest; close the open region with # mutare:ignore-end first"}
  end

  defp scope_error_message({:unterminated_region, line}, file) do
    {:unterminated_region, line,
     "#{file}:#{line}: # mutare:ignore-start is never closed — add # mutare:ignore-end " <>
       "(or use # mutare:ignore-file to suppress the whole file)"}
  end

  @doc false
  # The comments in `source` that claim the `mutare:` namespace without spelling a recognized
  # directive, as `{comment_line, head}` pairs sorted by line — `head` is the `mutare:<verb>`
  # text as the user wrote it (spacing preserved), for echoing back in the warning. The
  # container's `unknown` field, for a caller holding only the source.
  @spec unknown_directives(String.t()) :: [{pos_integer(), String.t()}]
  def unknown_directives(source) when is_binary(source) do
    source
    |> Sourceror.parse_string!()
    |> directives_from_ast()
    |> Map.fetch!(:unknown)
  end

  # The unknown-verb comments among `comments` (every comment in the file). The namespace is
  # reserved: a comment matching the anchored `mutare:` prefix but no directive parser is a
  # typo'd verb (`ingore`), a colon-detached one (`mutare: ignore`), or a directive this version
  # doesn't know — each is surfaced rather than left silently inert, so a future directive (or a
  # slip) can't read as "no directive here".
  defp unknown_verbs(comments) do
    comments
    |> Enum.filter(fn %{text: text} = comment ->
      Regex.match?(@namespace, text) and is_nil(parse_directive(comment))
    end)
    |> Enum.map(fn %{line: line, text: text} -> {line, head(text)} end)
    |> Enum.sort()
  end

  # The `mutare:<verb>` head of an unknown-verb comment, as written. Total for any
  # `@namespace` match: `@head`'s verb token is `[\w-]*`, so at worst the head is
  # a bare `mutare:`.
  defp head(text) do
    [head | _captures] = Regex.run(@head, text)
    head
  end

  @doc false
  # The actionable tail for an unknown-verb warning: `; did you mean # mutare:ignore?` when
  # the verb is a near-miss of a recognized one (same Jaro threshold as the label
  # suggestions), otherwise the recognized-verb list. One or the other, never both.
  @spec verb_hint(String.t()) :: String.t()
  def verb_hint(head) do
    %{"verb" => verb} = Regex.named_captures(@head, head)

    case closest(verb, @known_verbs) do
      nil -> " (recognized: #{Enum.map_join(@known_verbs, ", ", &"# mutare:#{&1}")})"
      best -> "; did you mean # mutare:#{best}?"
    end
  end

  @doc false
  # The directive (if any) that suppresses a site at `line` for `mutator`/`target` (the site's
  # `variant` label list). Candidates are the line's own directives plus every scoped directive
  # covering the line. Returns the most specific match — an exact `[family:label]` over a bare
  # `[family]`/`:all` — then, on a specificity tie, the *narrowest scope* (line over region over
  # file: the most locally-written reason is the one recorded), then source order. `target`
  # defaults to `:any` (the family-level "does any directive admit this family?" question).
  @spec directive_for(Directives.t(), pos_integer(), atom(), Directive.query()) ::
          Directive.t() | nil
  def directive_for(%Directives{by_line: by_line, scoped: scoped}, line, mutator, target \\ :any) do
    candidates = Map.get(by_line, line, []) ++ Enum.filter(scoped, &Directive.covers?(&1, line))

    case Enum.filter(candidates, &Directive.applies_to?(&1, mutator, target)) do
      [] ->
        nil

      matches ->
        # Ranking on the *intrinsic* `source_order` — rather than relying on `Enum.max_by`
        # returning the first maximal element of a pre-sorted list — keeps the tie-break
        # self-contained: `directives_from_ast/1` stamps the order, this reads it.
        Enum.max_by(
          matches,
          &{Directive.match_specificity(&1, mutator, target), Directive.scope_rank(&1),
           -&1.source_order}
        )
    end
  end

  @doc false
  # Strictly validate every qualified `[family:label]` filter against `vocabulary`, raising
  # `Mutare.Ignore.SpecError` on the first whose family is *known* but whose label can't be resolved
  # (with a "did you mean"). An unknown family is left to the soft `ineffective/2` warning, and a
  # bare `[family]` is never checked here. `file` locates the directive. Returns `:ok` otherwise.
  @spec validate!(
          Directives.t(),
          %{String.t() => :none | MapSet.t(String.t())},
          String.t()
        ) :: :ok
  def validate!(%Directives{} = directives, vocabulary, file) do
    # Iterate in a stable, top-to-bottom order so the *first* bad qualifier raised is deterministic
    # (`Directives.all/1` is document-ordered, then a sorted scan of each filter's entries — a
    # filter's entries are a `MapSet`, so without the sort the reported error would be whichever
    # entry hash-iteration happened to reach first, not the one nearest the top of the file).
    for directive <- Directives.all(directives),
        {family, label} <- Enum.sort(qualified_entries(directive)) do
      # Located at the directive comment itself, not the suppressed line — the
      # two can be several lines apart when a comment block sits between them,
      # and the error is about the directive's own text.
      validate_entry!(family, label, directive.comment_line, vocabulary, file)
    end

    :ok
  end

  @doc false
  # Whether any directive carries a qualified `[family:label]` entry — the only kind `validate!/3`
  # checks, so the transform skips building the variant vocabulary when every filter is bare.
  @spec any_qualified?(Directives.t()) :: boolean()
  def any_qualified?(%Directives{} = directives) do
    directives
    |> Directives.all()
    |> Enum.any?(&(qualified_entries(&1) != []))
  end

  defp qualified_entries(%Directive{mutators: :all}), do: []

  # The qualified entries `validate!/3` checks: a real, *named* label. The whole-family `:any` and
  # the empty-label `""` (a malformed `[family:]` qualifier) are both excluded — the former is a
  # bare filter, the latter a slip left to the soft `ineffective/2` warning, never a hard abort.
  defp qualified_entries(%Directive{mutators: %MapSet{} = set}),
    do: for({family, label} <- set, label not in [:any, ""], do: {family, label})

  defp validate_entry!(family, label, line, vocabulary, file) do
    case Map.get(vocabulary, family) do
      # The family is not in the active vocabulary. We can't *prove* this is a typo — it is equally
      # an excluded custom family (a `--mutators` subset, a removed config entry), which we have no
      # way to enumerate. So, exactly like a bare `[family]` typo, it stays lenient: a soft
      # `ineffective/2` warning, never a hard abort. Hard errors are reserved for a *known* family
      # with a wrong/absent label (`:none`/`:unknown_variant` below), where the mistake is certain.
      nil ->
        :ok

      :none ->
        raise SpecError,
          reason: :no_variants,
          file: file,
          line: line,
          family: family,
          label: label,
          message:
            "#{file}:#{line}: the #{family} mutator declares no variant labels, so " <>
              "# mutare:ignore[#{family}:#{label}] can't select one — use the bare " <>
              "# mutare:ignore[#{family}] to suppress the whole family"

      %MapSet{} = labels ->
        unless MapSet.member?(labels, label) do
          raise SpecError,
            reason: :unknown_variant,
            file: file,
            line: line,
            family: family,
            label: label,
            message:
              "#{file}:#{line}: #{inspect(label)} is not a #{family} variant in " <>
                "# mutare:ignore[#{family}:#{label}]" <>
                suggestion(label, MapSet.to_list(labels)) <>
                " (known: #{labels |> Enum.sort() |> Enum.join(", ")})"
        end
    end
  end

  # A `; did you mean "x"?` clause for the closest candidate, or "" when nothing is close
  # enough; the caller always appends the full `(known: …)` list as the fallback.
  defp suggestion(name, candidates) do
    case closest(name, candidates) do
      nil -> ""
      best -> "; did you mean #{inspect(best)}?"
    end
  end

  # The closest candidate by Jaro distance, or `nil` when nothing is close enough (the
  # `>= 0.8` threshold avoids a misleading suggestion for a wild typo). This fires for a
  # *near-miss* — `nagate` → `negate`, `tru` → `true`, a symbol slip like `>==` → `>=`, or
  # a verb typo `ingore` → `ignore`. It deliberately stays silent for a cross-*spelling*
  # miss (a word for a symbol family, `lte` for `<=`), where no string distance is
  # meaningful; the callers' known-list fallback is the actionable hint in that case.
  defp closest(name, candidates) do
    candidates
    |> Enum.map(&{&1, String.jaro_distance(name, &1)})
    # `>=` vs `>` at exactly 0.8 is impractical to pin with a real test: `String.jaro_distance/2`
    # is a float computed via several divisions, and a value that mathematically converges to
    # 0.8 lands on a *different* IEEE-754 double than the `0.8` literal here (observed:
    # 0.7999999999999999) — so a near-miss engineered to "hit the boundary" actually falls just
    # short and can't distinguish the two operators.
    # mutare:ignore[relational] impractical to test at the float boundary, per above
    |> Enum.filter(fn {_candidate, distance} -> distance >= 0.8 end)
    |> Enum.max_by(fn {_candidate, distance} -> distance end, fn -> nil end)
    |> case do
      {best, _distance} -> best
      nil -> nil
    end
  end

  @doc false
  # For an *ineffective* directive: the first following line — within the multi-line expression
  # that starts at the directive's suppressed line — carrying a mutant the directive would have
  # suppressed, or `nil`. Powers the misplacement hint in the warning: a directive covers exactly
  # one line, and a long pipe reads as one logical statement, so annotating it "from the top" (the
  # directive above `digested_files`, the mutated `ordered:`/`timeout:` two `|>` steps down) is the
  # most common miss. The scan is bounded by the expression's own span, so the hint never points
  # into an unrelated statement further down the file. `directives` is the container the
  # directive came from: its `end_lines` (harvested with the directives) supply that span, so
  # no AST is needed here.
  @spec misplacement_hint(Directives.t(), Directive.t(), [
          {pos_integer() | nil, atom(), Directive.query()}
        ]) :: pos_integer() | nil
  def misplacement_hint(%Directives{}, %Directive{scope: scope}, _occupied) when scope != :line do
    # The one-line-coverage miss the hint explains can't happen to a scoped directive — an
    # ineffective `-file`/region really did cover every line it names and found nothing.
    nil
  end

  def misplacement_hint(%Directives{end_lines: end_lines}, %Directive{} = directive, occupied) do
    case Map.get(end_lines, directive.line) do
      end_line when is_integer(end_line) and end_line > directive.line ->
        occupied
        |> Enum.filter(fn {line, mutator, target} ->
          is_integer(line) and line > directive.line and line <= end_line and
            Directive.applies_to?(directive, mutator, target)
        end)
        |> Enum.map(fn {line, _mutator, _target} -> line end)
        |> Enum.min(fn -> nil end)

      _no_multi_line_expression ->
        nil
    end
  end

  @doc false
  # For each of `lines`, the last line of the widest expression that *starts* at it; a line no
  # node starts on (a blank line, a comment-only line, past EOF) gets no entry. One prewalk
  # serves every line, and `[]` walks nothing. `Sourceror.get_range/1` computes a node's start
  # from its leftmost token, so a pipe chain's node starts at its first operand's line even though
  # the `|>` operator meta sits further down — which is exactly the span the misplacement hint
  # scans.
  @spec expression_end_lines(Macro.t(), [pos_integer()]) :: %{pos_integer() => pos_integer()}
  def expression_end_lines(_ast, []), do: %{}

  def expression_end_lines(ast, lines) do
    wanted = MapSet.new(lines)

    {_ast, end_lines} =
      Macro.prewalk(ast, %{}, fn
        {_form, meta, _args} = node, acc when is_list(meta) ->
          case node_range(node) do
            %Sourceror.Range{start: start_pos, end: end_pos} ->
              start = start_pos[:line]
              stop = end_pos[:line]

              if MapSet.member?(wanted, start),
                do: {node, Map.update(acc, start, stop, &max(&1, stop))},
                else: {node, acc}

            _no_range ->
              {node, acc}
          end

        node, acc ->
          {node, acc}
      end)

    end_lines
  end

  # `Sourceror.get_range/1` is total over real source nodes but can return `nil` (and, defensively,
  # raise) on synthetic/degenerate shapes; a missing range just means no hint from that node.
  defp node_range(node) do
    Sourceror.get_range(node)
  rescue
    _ -> nil
  end

  @doc false
  # The directives in `directives` that suppressed *nothing* (sorted by line): a bare-family typo,
  # a valid variant label absent on this line, an empty `[]`, a standalone directive on the wrong
  # line, or a family that produced no mutant there — every directive `Directive.applies_to?/3`
  # rejects for every occupied `{mutator, variant}` on a line its scope covers. (A qualified bad
  # label on a *known* family never reaches here — it is a hard `validate!/3` error.) `occupied` is
  # the `{line, mutator, variant}` (the `variant` label list) of each recorded site, passed as plain
  # tuples so this module stays unaware of the `Mutare.Site` representation. Detection reflects the
  # active config — a family disabled by `--mutators` produces no site, so a directive naming only
  # it is reported. Scoped directives are held to the same bar: an `ignore-file` in a mutant-free
  # file, or a region whose span matches nothing, is a stale annotation worth the warning.
  @spec ineffective(Directives.t(), [
          {pos_integer() | nil, atom(), Directive.query()}
        ]) :: [Directive.t()]
  def ineffective(%Directives{} = directives, occupied) do
    directives
    |> Directives.all()
    |> Enum.reject(fn directive ->
      Enum.any?(occupied, fn {line, mutator, result} ->
        Directive.covers?(directive, line) and Directive.applies_to?(directive, mutator, result)
      end)
    end)
    |> Enum.sort_by(& &1.line)
  end

  # Every comment Sourceror attached to a node, flattened. A comment lands in
  # exactly one node's `:leading_comments`/`:trailing_comments`, so no
  # deduplication is needed. (Which bucket it lands in is unreliable for the
  # trailing-vs-standalone question — `previous_eol_count` is the signal.)
  defp comments(ast) do
    {_ast, acc} =
      Macro.prewalk(ast, [], fn
        {_form, meta, _args} = node, acc when is_list(meta) ->
          leading = Keyword.get(meta, :leading_comments, [])
          # Sourceror always sets `:trailing_comments` (even to `[]`) on every node's meta this
          # prewalk visits — verified across this whole file's own AST, 0 nodes missing the key —
          # so the `[]` default here is unreachable in practice; dropping it is equivalent.
          # mutare:ignore[default_drop] equivalent, per above
          trailing = Keyword.get(meta, :trailing_comments, [])
          # This node's own leading/trailing relative order matters (fixed up for real by the
          # `Enum.sort_by(& &1.line)` + stamped `source_order` in `directives_from_ast/1`), but
          # swapping this merge to `acc ++ trailing` only reorders *this node's own pair*
          # relative to `acc` (comments from other, already-visited nodes) — observable only if
          # two directives from different nodes land on the identical suppressed line, which
          # (see the `directives_from_ast/1` sort_by note above) normal source can't produce.
          # mutare:ignore[operand_swap] equivalent, per above
          {node, leading ++ trailing ++ acc}

        node, acc ->
          {node, acc}
      end)

    # `prewalk` accumulates in a visit order that does *not* match document order (it prepends,
    # and folds a node's leading *before* its trailing comments). Ordering into true source order
    # — and stamping each directive's `source_order` for the `directive_for/4` tie-break — is
    # `directives_from_ast/1`'s job, kept next to the index that depends on it.
    acc
  end

  # A line directive from its comment and the `rest` after the verb.
  defp to_directive(comment, rest, source_order, comment_lines) do
    {mutators, reason} = parse_rest(rest)

    %Directive{
      line: suppressed_line(comment, comment_lines),
      comment_line: comment.line,
      mutators: mutators,
      reason: reason,
      source_order: source_order
    }
  end

  # Split the text after `mutare:ignore` into a mutator filter and a reason. A
  # leading `[...]` is the filter (otherwise the filter is `:all`); whatever
  # remains, trimmed, is the reason (or `nil` when blank).
  defp parse_rest(rest) do
    trimmed = String.trim_leading(rest)

    case Regex.named_captures(@filter, trimmed) do
      %{"families" => families, "reason" => reason} ->
        {parse_filter(families), clean_reason(reason)}

      nil ->
        # No `[...]` matched. A **malformed filter** — a leading `[` with no closing `]`
        # (`# mutare:ignore[relational`) — must NOT degrade to `:all`: that would silently
        # suppress *every* mutant on the line, the one dangerous direction. Treat it as an
        # empty filter (matches nothing, fail-safe toward running the mutant), surfaced by
        # `ineffective/2` as a soft warning. Text not starting with `[` is an ordinary reason.
        if String.starts_with?(trimmed, "[") do
          {MapSet.new([]), nil}
        else
          {:all, clean_reason(rest)}
        end
    end
  end

  # The bracket body → a set of `{family, target}` entries. Split on commas and
  # whitespace; an empty body yields an empty set, which matches nothing. Each
  # entry is `family` or `family:label`; both halves are folded by
  # `Mutare.Mutator.normalize_label/1` (case-insensitive matching — the *same* helper the
  # declaring/recording sides use, so the two can't drift), and the split is on the *first* `:`
  # only, so a multi-character operator label (`!==`) is kept whole. A bare `:` can't appear in a
  # family name.
  defp parse_filter(families) do
    families
    # `trim: true` drops every empty string the split produces — including the run of
    # empties a *single*-char class (no `+`) or a lazy `+?` leaves between adjacent
    # separators — so `~r/[,\s]/` and `~r/[,\s]+?/` both trim down to the exact same
    # result as `~r/[,\s]+/` for every input; only an empty pattern (`~r//`, splitting
    # every character) actually differs.
    # mutare:ignore[regex] equivalent under trim: true, per above
    |> String.split(~r/[,\s]+/, trim: true)
    |> Enum.map(&parse_entry/1)
    |> MapSet.new()
  end

  # A bare `[family]` (no colon) is the whole-family entry `:any`. A `family:label` token is the
  # qualified entry `{family, label}`. A **trailing colon with no label** (`[relational:]`, or a
  # `[relational: >]` whose stray space splits the colon off its label) splits to `[family, ""]`
  # and so falls through to the general clause as the empty-label entry `{family, ""}` — a
  # *malformed qualifier*, not a bare family: it matches no real variant, so it suppresses
  # **nothing** and is surfaced by `ineffective/2` as a soft warning. This is deliberately *not*
  # whole-family suppression: a silent `:any` would hide every mutant the user meant to keep (the
  # dangerous direction, with no `validate!`/`ineffective` net). Nor is it a hard error — a
  # *missing* label is a slip, not a *named* wrong one, so (like a bare typo) it stays lenient.
  defp parse_entry(token) do
    case String.split(token, ":", parts: 2) do
      [family] -> {Mutator.normalize_label(family), :any}
      [family, label] -> {Mutator.normalize_label(family), Mutator.normalize_label(label)}
    end
  end

  defp clean_reason(text) do
    case String.trim(text) do
      "" -> nil
      reason -> reason
    end
  end

  # A trailing directive (no newline before it ⇒ code shares its line) suppresses
  # its own line; a standalone one suppresses the next line of *code*, reading
  # through the contiguous block of standalone comments below it — so a directive
  # works at either end of an explanatory comment block. A blank line is not a
  # comment line, so it ends the walk (the directive then targets the blank line,
  # suppresses nothing, and is surfaced by `ineffective/2` — the conservative
  # reading of a detached block).
  defp suppressed_line(%{line: line, previous_eol_count: 0}, _comment_lines), do: line
  defp suppressed_line(%{line: line}, comment_lines), do: next_code_line(line + 1, comment_lines)

  defp next_code_line(line, comment_lines) do
    if line in comment_lines,
      do: next_code_line(line + 1, comment_lines),
      else: line
  end
end
